[package]
name = "app-launch"
version = "0.1.3"
authors = ["u296"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="*"
freedesktop_entry_parser="*"
itertools="*"
